

server:
  port: 8080

service:
  open-weather:
    api-data:
      endpoint: https://api.openweathermap.org/data/2.5/weather
    appId: MDQ2NzFkYWYxODM2OTdlMWMyNTA3NTcyZTQ4OGRmNzA=
    units: metric
  umbrella:
    weathers:
      - Thunderstorm
      - Drizzle
      - Rain



###Database related
spring:
  main:
    banner-mode: off
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console